### ISSUE TITLE
How to run the project？

### ISSUE THREAD

**Issue by xxxsf** [Kimbatt/js13k-2023#1]

**Comment by Kimbatt** [comment]
You need Typescript (because the code is written in typescript), and a local http server (because the code uses modules, and modules cannot be used when opening a local file).
You can download Typescript from here: https://www.typescriptlang.org/download
You can use any http server, for example this one: https://github.com/http-party/http-server

Then, from the `readable source` folder, run the `tsc` command to compile the typescript files to javascript. (You can run the `tsc -w` command to automatically recompile the code when you change it)
From the same folder, run the http server (defaults to port 8080).
Finally, you can open http://localhost:8080/

**Comment by xxxsf** [comment]
Thx, This game is intersting! I like it
